import { useEffect, useState } from "react";
import { Store, ExternalLink } from "lucide-react";
import { api } from "../api/client";

type Item = { slug: string; name: string; version: string; category: string; description: string; publisher: string; status: string; package_type: string; compatibility: string; integrity: string; docs_url: string };
type Compatibility = { package_type: string; format_version: string; nexus_versions: string[]; runtimes: string[]; trust: string };
export function MarketplacePage() {
  const [items, setItems] = useState<Item[]>([]); const [matrix, setMatrix] = useState<Compatibility[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.getMarketplaceCatalog(), api.getMarketplaceCompatibility()]).then(([next, compat]) => { setItems(next); setMatrix(compat); }).catch(e => setError(e instanceof Error ? e.message : "Unable to load marketplace")); }, []);
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-nexus-text">Marketplace</h1><p className="text-nexus-textMuted">NEXUS integrations, SDKs, compatibility and trust metadata.</p></div>{error&&<p role="alert" className="text-red-300">{error}</p>}<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.slug} className="rounded-xl border border-nexus-border bg-nexus-surface p-5"><div className="flex items-center gap-3"><Store className="h-5 w-5 text-nexus-primary"/><div className="flex-1"><h2 className="font-semibold text-nexus-text">{item.name}</h2><p className="text-xs text-nexus-textMuted">{item.category} · v{item.version}</p></div></div><p className="mt-4 text-sm text-nexus-textMuted">{item.description}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-nexus-textMuted"><span className="rounded-full border border-nexus-border px-2 py-1">{item.package_type}</span><span className="rounded-full border border-nexus-border px-2 py-1">{item.compatibility}</span><span className="rounded-full border border-nexus-border px-2 py-1">{item.integrity}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-nexus-textMuted">{item.publisher} · {item.status}</span><a className="btn-secondary inline-flex items-center gap-2" href={item.docs_url.startsWith("/") ? item.docs_url : "#"} target={item.docs_url.startsWith("http") ? "_blank" : undefined} rel="noreferrer">Docs <ExternalLink className="h-4 w-4"/></a></div></article>)}</div>
    <section className="rounded-xl border border-nexus-border bg-nexus-surface p-5"><h2 className="font-semibold">Compatibility & trust</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{matrix.map(m=><div key={m.package_type} className="rounded-lg border border-nexus-border p-3"><div className="font-medium">{m.package_type}</div><div className="text-xs text-nexus-textMuted mt-1">format {m.format_version} · {m.nexus_versions.join(", ")}</div><div className="text-xs text-nexus-textMuted">{m.runtimes.join(" · ")}</div><div className="text-xs mt-2">trust: {m.trust}</div></div>)}</div></section>
  </div>;
}
